import { Poppins } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/Header";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import {ui} from "@clerk/themes";
import { Toaster } from "sonner";

const poppins = Poppins({
  weight: ['400', '700'], // Specify the weights you need
  subsets: ['latin'],
  display: 'swap', // Ensures the font is displayed as soon as it is available
  variable: '--font-poppins', // Define a CSS variable name
});

export const metadata = {
  title: "Medimeet - Connect with Doctors Online",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <head />
      <body className="min-h-full flex flex-col">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          
          <ClerkProvider ui={ui}>
            <Header />
            <Toaster richColors/>
            {children}
            
            </ClerkProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
